create extension if not exists pg_trgm with schema extensions;

create table if not exists public.serviceops_customers (
  customer_id text primary key,
  customer_number text,
  display_name text,
  email text,
  phone text,
  alt_phone text,
  street text,
  city text,
  postal_code text,
  raw jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists serviceops_customers_display_name_idx on public.serviceops_customers using gin (display_name gin_trgm_ops);
create index if not exists serviceops_customers_email_idx on public.serviceops_customers (lower(email));
create index if not exists serviceops_customers_phone_idx on public.serviceops_customers (phone);

create table if not exists public.serviceops_customer_locations (
  location_id text primary key,
  customer_id text not null,
  name text,
  street text,
  city text,
  province text,
  postal_code text,
  raw jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists serviceops_customer_locations_customer_idx on public.serviceops_customer_locations (customer_id);

create table if not exists public.serviceops_service_requests (
  request_id text primary key,
  source_row integer,
  submitted_at timestamptz,
  closed_at timestamptz,
  status text,
  pipeline_state text,
  customer_name text,
  striven_customer_id text,
  issue text,
  appliance text,
  city text,
  postal_code text,
  needs_review boolean not null default false,
  last_error text,
  striven_opportunity_id text,
  striven_sales_order_id text,
  raw jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists serviceops_requests_customer_idx on public.serviceops_service_requests (striven_customer_id);
create index if not exists serviceops_requests_open_idx on public.serviceops_service_requests (closed_at, submitted_at desc);

create table if not exists public.serviceops_work_orders (
  work_order_id text primary key,
  sales_order_number text,
  customer_id text,
  customer_name text,
  status text,
  created_at timestamptz,
  scheduled_at timestamptz,
  technician text,
  title text,
  location text,
  summary text,
  raw jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists serviceops_work_orders_customer_idx on public.serviceops_work_orders (customer_id);
create index if not exists serviceops_work_orders_so_idx on public.serviceops_work_orders (sales_order_number);

create table if not exists public.serviceops_technician_schedule (
  event_id text primary key,
  technician text not null,
  title text,
  location text,
  start_at timestamptz not null,
  end_at timestamptz,
  source text not null default 'google',
  visible_to_serviceops boolean not null default true,
  work_order_id text,
  sales_order_number text,
  raw jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists serviceops_schedule_date_idx on public.serviceops_technician_schedule (start_at);
create index if not exists serviceops_schedule_tech_idx on public.serviceops_technician_schedule (technician);

create table if not exists public.serviceops_opportunity_requests (
  id bigint generated by default as identity primary key,
  request_id text not null,
  source_row integer,
  customer_id text not null,
  status text not null default 'pending_operator_review',
  operator_note text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  striven_opportunity_id text,
  error_message text
);

create index if not exists serviceops_opportunity_requests_request_idx on public.serviceops_opportunity_requests (request_id);
create index if not exists serviceops_opportunity_requests_status_idx on public.serviceops_opportunity_requests (status, created_at desc);

create table if not exists public.tool_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tool_name text not null,
  actor text not null default 'chatgpt_app',
  input jsonb not null default '{}'::jsonb,
  ok boolean not null,
  result_summary text,
  error_message text
);

create index if not exists tool_audit_log_tool_idx on public.tool_audit_log (tool_name, created_at desc);

alter table public.serviceops_customers enable row level security;
alter table public.serviceops_customer_locations enable row level security;
alter table public.serviceops_service_requests enable row level security;
alter table public.serviceops_work_orders enable row level security;
alter table public.serviceops_technician_schedule enable row level security;
alter table public.serviceops_opportunity_requests enable row level security;
alter table public.tool_audit_log enable row level security;
